### ISSUE TITLE
r24 fails to build on IA32 (32-bit x86)

### ISSUE THREAD

**Issue by jbeich** [EleonoreMizo/fmtconv#23]
Regressed by 5216839b9aff. From [error log](https://github.com/EleonoreMizo/fmtconv/files/6995282/vapoursynth-fmtconv-r24.log):
```c++
In file included from src/fmtcl/Dither.cpp:29:
src/fmtcl/Dither.h:210:26: error: unknown type name '__m128i'
        static fstb_FORCEINLINE __m128i
                                ^
src/fmtcl/Dither.h:212:26: error: unknown type name '__m128i'
        static fstb_FORCEINLINE __m128i
                                ^
src/fmtcl/Dither.h:213:33: error: unknown type name '__m128i'
                       remap_tpdf_vec (__m128i d) noexcept;
                                       ^
src/fmtcl/Dither.cpp:1662:17: error: out-of-line definition of 'generate_dith_n_vec' does not match any declaration in 'fmtcl::Dither'
__m128i Dither::generate_dith_n_vec (uint32_t &rnd_state) noexcept
                ^~~~~~~~~~~~~~~~~~~
src/fmtcl/Dither.cpp:1704:17: error: out-of-line definition of 'remap_tpdf_vec' does not match any declaration in 'fmtcl::Dither'
__m128i Dither::remap_tpdf_vec (__m128i d) noexcept
                ^~~~~~~~~~~~~~
src/fmtcl/Dither.cpp:1532:23: error: use of undeclared identifier 'generate_dith_n_vec'
                        __m128i                 dith_n = generate_dith_n_vec <TN_FLAG> (rnd_state);
                                                         ^
src/fmtcl/Dither.cpp:1094:2: note: in instantiation of function template specialization 'fmtcl::Dither::process_seg_common_int_int_sse2<false, false, fmtcl::SplFmt_INT8, 8, fmtcl::SplFmt_INT16, 9, (lambda at src/fmtcl/Dither.cpp:1097:3)>' requested here
        process_seg_common_int_int_sse2 <
        ^
src/fmtcl/Dither.cpp:615:4: note: in instantiation of function template specialization 'fmtcl::Dither::process_seg_ord_int_int_sse2<false, false, false, fmtcl::SplFmt_INT8, 8, fmtcl::SplFmt_INT16, 9>' requested here
                        fmtcl_Dither_SET_FNC_INT_SSE2,
                        ^
src/fmtcl/Dither.cpp:1662:17: note: must qualify identifier to find this declaration in dependent base class
__m128i Dither::generate_dith_n_vec (uint32_t &rnd_state) noexcept
                ^
```

**Comment by EleonoreMizo** [comment]
Works here but I guess why it could fail. Does c6e76cb3ed83e97294053ffc3e53b4be07968554 fix the problem?

**Comment by jbeich** [comment]
Thanks, [builds fine](https://github.com/EleonoreMizo/fmtconv/files/6995746/vapoursynth-fmtconv-r24.log) now.
